apiVersion: v1
kind: Service
metadata:
  name: udacity-devops-capstone-service
  labels:
    app: udacity-devops-capstone
spec:
  type: LoadBalancer
  selector:
    app: udacity-devops-capstone
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-devops-capstone-deployment
  labels:
    app: udacity-devops-capstone
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-devops-capstone
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udacity-devops-capstone
    spec:
      containers:
        - image: tamerthamoqa/udacity-devops-capstone
          imagePullPolicy: Always
          name: udacity-devops-capstone
          ports:
            - containerPort: 80